src/pages/NetworkList.tsx
=> Fix network list back button

src/App.tsx, src/components/CopyBox.tsx, src/components/CopyButton.tsx, src/components/Header.tsx, src/contexts/PriceContext.tsx, src/hooks/useTokenParams.ts, src/pages/Token.tsx, src/pages/TokenList.tsx
Chia price is fetched from CoinGecko, CAT prices are fetched from Dexie.
=> Show USD balance for XCH and CATs

src/pages/ImportWallet.tsx, src/pages/Login.tsx
Fixed 2 pages still not having correct safe area padding.
=> quick fix to pages missing safe area padding

crates/sage-wallet/src/wallet/offer/unlock_assets.rs
This is a workaround for erroneous offers created by the Chia reference wallet.
=> Fix offers with settlement CATs with 0 amount

src/locales/zh-CN/messages.po
=> Chinese Translation (zh-CN)

package.json, pnpm-lock.yaml, src/components/Layout.tsx, src/components/Nav.tsx, src/components/ui/tooltip.tsx, src/locales/de-DE/messages.po, src/locales/en-US/messages.po, src/locales/zh-CN/messages.po
This PR adds a collapsible state to the left nav. https://github.com/xch-dev/sage/issues/132
This new behavior only triggers in wider layouts. Functionality does not change for mobile portrait mode sized views.
- Implemented a collapsible sidebar feature using local storage to remember the user's preference.
- Added a new tooltip component to provide contextual information for navigation links in the sidebar.
- Enhanced the Nav component to support tooltips for each navigation link based on the sidebar's collapsed state.
This PR takes a dependency on ` @radix-ui/react-tooltip`
=> Enhance sidebar functionality and add tooltips for navigation items

src/components/TokenGridView.tsx, src/components/TokenListView.tsx, src/components/ViewToggle.tsx, src/lib/utils.ts, src/pages/TokenList.tsx, src/types/TokenViewProps.ts
This PR adds the ability to switch between the current grid view and a list view a tokens. That choice is save in local storage and restored between sessions.
fixes: https://github.com/xch-dev/sage/issues/275
=> Token listview

src/contexts/WalletConnectContext.tsx
see https://tauri.app/reference/javascript/api/namespacewindow/#platform-specific-4
=> [WalletConnect] Make sure platform-specific api not used on mobile

src/components/NftCard.tsx, src/components/NftCardList.tsx
Make sure the `NftCard` component correctly re-render when the nft data change
=> Fix `NftCard` component update

src/components/selectors/DropdownSelector.tsx, src/components/selectors/NftSelector.tsx, src/components/selectors/TokenSelector.tsx, src/lib/utils.ts
Fix https://github.com/xch-dev/sage/issues/323
This PR adds the ability to search for tokens and nfts while creating an offer
- Change the text entry to execute a search (in addition to still allowing direct selection if an asset or nft id is entered)
- remove DropDownMenu* components from DropDownSelector as they steal focus.
=> Token and NFT selector search

crates/sage-api/src/requests/data.rs, crates/sage-cli/src/router.rs, crates/sage/src/endpoints/data.rs, src-tauri/src/commands.rs, src-tauri/src/lib.rs, src/bindings.ts, src/pages/Addresses.tsx
Fix https://github.com/xch-dev/sage/issues/280
- Add a card to the addresses page to check if the address exists in the wallet
- Add backend code to encode input address and see if the p2 puzzle hash is in the database
=> Check address

src/components/MultiSelectActions.tsx, src/components/NftCard.tsx, src/components/selectors/NftSelector.tsx, src/pages/MakeOffer.tsx
bug report from discord:
https://discord.com/channels/1220144003874553986/1220151049483059330/1349254745889439807
Adding an nft to offer from the nft card only adds the placeholder on the offer page. 
Fix tested for single and multiple nft additions.
=> fix adding to offer only adds placeholder

src/components/TokenGridView.tsx
TokenGridView was scrolling past the bottom of the screen.
fix https://github.com/xch-dev/sage/issues/379
=> Fix TokenGridView overscrolling bug

src/components/QRCodeDialog.tsx, src/components/StyledQrCode.tsx, src/components/TokenCard.tsx, src/lib/offerUpload.ts, src/pages/Offers.tsx
Fix https://github.com/xch-dev/sage/issues/148
Add context menu item on the offers page to view a qr code with the dexie link.
=> Dexie link QR code for offers

crates/sage-database/src/coin_states.rs, crates/sage/src/endpoints/data.rs, src/components/AmountCell.tsx, src/components/TransactionColumns.tsx, src/components/TransactionListView.tsx
like assets are only partially being summarized on the TX view
=> TX summary bug

lingui.config.js, src/contexts/LanguageContext.tsx, src/locales/es-MX/messages.po, src/pages/Settings.tsx
fix https://github.com/xch-dev/sage/issues/410
=> Add Mexican Spanish locale

src/pages/CreateWallet.tsx
fix https://github.com/xch-dev/sage/issues/409
=> Fix new wallet not recognized by setting screen

src/components/OfferCard.tsx
fix #439 
One of these days we'll have to replace this dialog with the standard one if possible. I just don't wanna mess with wallet connect
=> cleanup layout slightly to keep labels within boundaries

src/components/Container.tsx, src/components/Header.tsx, src/components/Layout.tsx, src/pages/Settings.tsx
The settings page was not respecting the safe area inset on iphone. Now it is
=> Safe area inset settingpage

crates/sage-database/src/lib.rs, crates/sage-database/src/primitives/nfts.rs, crates/sage/src/sage.rs
Remove the collection id rust migration
Set the chia token ticker to match the config's network as rust_migration 1 on the new schema
=> update rust migration

src/components/dialogs/MakeOfferConfirmationDialog.tsx
Infinite render loop causing flicker of the NFT icon.
=> use a memo for the nft in MakeOfferConfirmation

src/pages/PeerList.tsx
Adds sync status to the peers page
=> sync status

src/pages/Login.tsx
=> tone down migrate warning

src/components/ConfirmationDialog.tsx, src/components/selectors/DropdownSelector.tsx, src/themes/colorful/theme.json
fix #598 
- transparency removed from drop down selector
- z-order fixed by using `createPortal`
- show background image form the theme on confirmation dialog
- use theme background color  for confirmation dialog tab content
=> fix transparency 

src/components/OptionGridView.tsx, src/components/confirmations/MintOptionConfirmation.tsx.tsx, src/pages/Option.tsx
Fix https://github.com/xch-dev/sage/issues/627
=> Fix Strike Asset label

src/components/selectors/AssetSelector.tsx, src/components/ui/masked-input.tsx, src/pages/IssueToken.tsx, src/pages/Send.tsx
fix https://github.com/xch-dev/sage/issues/644
=> TokenAmountInput precision not set in a number of places

src/pages/TokenList.tsx
FIX https://github.com/xch-dev/sage/issues/614
respects hidden tokens and search filtering.
please send bonus points via registered mail
=> Estimated wallet balance

src/lib/themes.ts
add `getUserThemes` back into theme discovery
fix https://github.com/xch-dev/sage/issues/669
=> load user themes

src/components/OwnedCoinsCard.tsx
fix https://github.com/xch-dev/sage/issues/572
=> Show selected coin total
